---

- name: Remove old docker packages
  ansible.builtin.package:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Ensure keyrings directory exists
  ansible.builtin.file:
    path: "/etc/apt/keyrings"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Add repo key and source
  block:
    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: docker repo apt source
      ansible.builtin.apt_repository:
        # signed-by=/etc/apt/keyrings/docker.gpg
        repo: "deb https://download.docker.com/linux/ubuntu focal stable"
        state: present

- name: Install docker and required packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
  register: docker_install

- name: Ensure required python modules are installed
  ansible.builtin.pip:
    name: docker

- name: Start docker service
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started