---
- name: Install Development Tools
  hosts: server
#  vars_files:
#    - ../vars/common.yml
#  #  - ../vars/secrets
  become: true # NEED TO RUN WITH -K (input root pw)
  gather_facts: true

  roles:
    - role: system
    # - role: git
    # - role: docker
    # - role: terraform