---
# This playbook prints a simple debug message
- name: Echo
  hosts: labsetup
  become_user: root
  become_method: sudo
  gather_facts: false

  tasks:
  - name: Print debug message
    debug:
      msg: Hello, world!