---
# This playbook prints a simple debug message
- name: Test Playbook
  hosts: server
  become: true # NEED TO RUN WITH -K (input root pw)
  gather_facts: true

  tasks:
  - name: Print debug message
    debug:
      msg: Hello, world!
